VillaLuxeMvcNet/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using VillaLuxeMvcNet.Models;

namespace VillaLuxeMvcNet.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

        public IActionResult HomeVilla()
        {
            return View();
        }

        public IActionResult AboutUs()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

VillaLuxeMvcNet/Controllers/VillasController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net.NetworkInformation;
using System.Security.Claims;
using VillaLuxeMvcNet.Filters;
using VillaLuxeMvcNet.Helpers;
using VillaLuxeMvcNet.Models;
using VillaLuxeMvcNet.Repositories;
using VillaLuxeMvcNet.Services;
using static System.Net.Mime.MediaTypeNames;
using System.Security.Claims;
using Amazon.Runtime.Internal.Util;


namespace VillaLuxeMvcNet.Controllers
{
    public class VillasController : Controller
    {
        /*private RepositoryVillas repo;*/
        private IRepositoryVillas service;
        private HelperPathProvider helperPathProvider;
        private ServiceStorageAWS serviceStorage;
        private ServiceAWSCache serviceCache;

        public VillasController(IRepositoryVillas service, HelperPathProvider helperPathProvider, ServiceStorageAWS storageAWS, ServiceAWSCache serviceCache)
        {
            /* this.repo = repo;*/
            this.service = service;
            this.helperPathProvider = helperPathProvider;
            this.serviceStorage = storageAWS;
            this.serviceCache = serviceCache;
        }

        public async Task<IActionResult> Index()
        {
            List<Villa> villas = await this.service.GetVillasUnicasAsync();
            return View(villas);
        }


        public async Task<IActionResult> DetallesVilla(int idvilla)
        {
            VillaFechasResevadas fechasReservadas = await this.service.FindVillaFechaReservadasAsync(idvilla);

            return View(fechasReservadas);
        }

        //----------------RESERVAS---------------

        [AuthorizeUsuarios]
        [HttpPost]
        public async Task<IActionResult> DetallesVilla(Reserva reserva)
        {
            try
            {
                int idusuario = int.Parse(User.FindFirst("IDUSUARIO").Value);
                reserva.IdUsuario = idusuario;
                reserva.Estado = "EN PROCESO";
                await this.service.CreateReserva(reserva);
                // Configurar un mensaje de confirmación en TempData
                /*TempData["ReservaConfirmada"] = "¡Reserva realizada con éxito!";*/

                // Redirigir de vuelta a la vista DetallesVilla
                return RedirectToAction("PagoReserva", new { idvilla = reserva.IdVilla });
            }
            catch (Exception ex)
            {
                // Configurar un mensaje de error en TempData
                TempData["ErrorReserva"] = ex.Message;

                // Redirigir de vuelta a la vista DetallesVilla
                return RedirectToAction("DetallesVilla", new { idvilla = reserva.IdVilla });
            }
        }

        public IActionResult PagoReserva(int idvilla)
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PagoReserva(Reserva reserva)
        {
            TempData["ReservaConfirmada"] = "¡Reserva realizada con éxito!";

            // Redirigir de vuelta a la vista DetallesVilla
            return RedirectToAction("MisReservas");
        }

        public async Task<IActionResult> MisReservas()
        {
            int idusuario = int.Parse(User.FindFirst("IDUSUARIO").Value);
            var reservas = await this.service.GetMisReservas(idusuario);
            return View(reservas);
        }

        public async Task<IActionResult> DeleteReserva(int idreserva)
        {
            await this.service.DeleteReserva(idreserva);
            return RedirectToAction("MisReservas");
        }
        public async Task<IActionResult> DeleteVilla(int idvilla)
        {
            List<Imagen> imagenes = await this.service.GetImagenesVilla(idvilla);
            foreach (var imagen in imagenes)
            {
                await this.serviceStorage.DeleteFileAsync(imagen.Imgn);
                await this.service.DeleteImagenes(imagen.IdImagen);
            }
            await this.service.DeleteVilla(idvilla);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AllReservasVilla(int idvilla)
        {
            // Obtener la lista de reservas
            var reservas = await this.service.GetReservasByIdVillaVistaAsync(idvilla);

            if (reservas == null)
            {
                return View();
            }
            else
            {
                // Convertir las reservas a MisReservas
                List<MisReservas> misReservas = reservas.Select(r => new MisReservas
                {
                    IdReserva = r.IdReserva,
                    IdUsuario = r.IdUsuario,
                    IdVilla = r.IdVilla,
                    FechaInicio = r.FechaInicio,
                    FechaFin = r.FechaFin,
                    PrecioTotal = r.PrecioTotal,
                    Estado = r.Estado,
                    Nombre = r.Nombre,
                    Direccion = r.Direccion,
                    Ubicacion = r.Ubicacion,
                    Imagen = r.Imagen
                }).ToList();

                // Pasar las MisReservas a la vista
                return View(misReservas);
            }

        }

        public IActionResult CreateVilla()
        {
            return View();
        }

        /*[HttpPost]
        public async Task<IActionResult> CreateVilla(VillaTabla villa, List<IFormFile> imagen, IFormFile imagenCollage)
        {
            villa.ImagenCollage = imagenCollage.FileName;
            VillaTabla villaT = await this.service.CreateVillaAsync(villa);


            foreach (IFormFile img in imagen)
            {
                string path =
               this.helperPathProvider.MapPath
               (img.FileName, Folders.Images);
                //SUBIMOS EL FICHERO UTILIZANDO Stream
                using (Stream stream = new FileStream(path, FileMode.Create))
                {
                    //MEDIANTE IFormFile COPIAMOS EL CONTENIDO DEL FICHERO
                    //AL STREAM
                    await img.CopyToAsync(stream);
                }

                string urlPath =
                    this.helperPathProvider.MapUrlPath(img.FileName
                    , Folders.Images);

                //BLOBS, recoger imagen e insertarla
                await this.service.InsertarImagenes(villaT.IdVilla, urlPath);
            }

            string pathBanner =
              this.helperPathProvider.MapPath
              (imagenCollage.FileName, Folders.Images);
            //SUBIMOS EL FICHERO UTILIZANDO Stream
            using (Stream stream = new FileStream(pathBanner, FileMode.Create))
            {
                //MEDIANTE IFormFile COPIAMOS EL CONTENIDO DEL FICHERO
                //AL STREAM
                await imagenCollage.CopyToAsync(stream);
            }

            string urlPathBanner =
                this.helperPathProvider.MapUrlPath(imagenCollage.FileName
                , Folders.Images);

            await this.service.InsertarImagenes(villaT.IdVilla, urlPathBanner);

            TempData["VillaCreada"] = "¡Villa Insertada con éxito!";

            // Redirigir de vuelta a la vista DetallesVilla
            return RedirectToAction("Index");
        }*/
        /*
                public async Task<IActionResult> DeleteImagenModificarBlobs(string containername, string blobname, int idvilla)
                {
                    await this.service.DeleteBlobAsync(containername, blobname);
                    return RedirectToAction("EditVillas", new { idvilla = idvilla });
                }*/

        [HttpPost]
        public async Task<IActionResult> EditVillas(VillaTabla villa, List<IFormFile> imagen)
        {
            await this.service.EditVilla(villa);


            foreach (IFormFile file in imagen)
            {
                string blobName = file.FileName;
                using (Stream stream = file.OpenReadStream())
                {
                    await this.serviceStorage
                        .UploadFileAsync(blobName, stream);
                }
                await this.service.InsertarImagenes(villa.IdVilla, blobName);
            }

            try
            {
                await this.service.EditVilla(villa);
                // Configurar un mensaje de confirmación en TempData
                TempData["VillaModificada"] = "¡Villa Modificada con éxito!";

                // Redirigir de vuelta a la vista DetallesVilla
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                // Configurar un mensaje de error en TempData
                TempData["ErrorVilla"] = ex.Message;

                // Redirigir de vuelta a la vista DetallesVilla
                return RedirectToAction("Index");
            }

        }

        [HttpPost]
        public async Task<IActionResult> CreateVilla(VillaTabla villa, List<IFormFile> imagen, IFormFile imagenCollage)
        {
            string blobNameCollage = imagenCollage.FileName;
            villa.ImagenCollage = imagenCollage.FileName;

            VillaTabla villaT = await this.service.CreateVillaAsync(villa);
            using (Stream stream = imagenCollage.OpenReadStream())
            {
                await this.serviceStorage
                    .UploadFileAsync(blobNameCollage, stream);
            }


            foreach (IFormFile file in imagen)
            {
                string blobName = file.FileName;
                using (Stream stream = file.OpenReadStream())
                {
                    await this.serviceStorage
                        .UploadFileAsync(blobName, stream);
                }
                await this.service.InsertarImagenes(villaT.IdVilla, blobName);

            }

            //string urlPath = await this.service.UploadImageAsync(imagen, "villasimagenes");
            //await this.repo.InsertarImagenes(villaT.IdVilla, urlPath);


            TempData["VillaCreada"] = "¡Villa Insertada con éxito!";

            // Redirigir de vuelta a la vista DetallesVilla

VillaLuxeMvcNet/Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "About Us";
}

<section class="bg-secondary py-5" style="background-color:#6a561ccc !important">
        <div class="container">
            <div class="row align-items-center py-5">
                <div class="col-md-8 text-white">
                    <h1>Sobre Nosotros</h1>
                    <hr>
                    <p>
                        Bienvenido a VillaLuxe, donde la elegancia y el lujo se funden para crear experiencias inolvidables. Con una pasión por el servicio excepcional y la atención meticulosa a cada detalle, nos enorgullece ofrecer una selección exclusiva de alojamientos de lujo en destinos de ensueño alrededor del mundo.
                        En VillaLuxe, nos esforzamos por superar las expectativas de nuestros huéspedes en cada estancia. Nuestras propiedades han sido cuidadosamente seleccionadas por su ubicación excepcional, diseño exquisito y comodidades de primer nivel, garantizando un refugio de lujo que cautivará sus sentidos y rejuvenecerá su espíritu.
                        ¡Esperamos darle la bienvenida pronto!
                    </p>
                </div>
                <div class="col-md-4">
                    <img src="~/img/about-hero.png" alt="About Hero">
                </div>
            </div>
        </div>
    </section>
    <!-- Close Banner -->

    <!-- Start Section -->
    <section class="container py-5">
        <div class="row text-center pt-5 pb-3">
            <div class="col-lg-9 m-auto">
                <h1 class="h1">Nuestros Servicios</h1>
                <p>
                    Ofrecemos servicios excepcionales para garantizar que cada aspecto de su estancia sea perfecto. Nuestro compromiso es proporcionar comodidad y satisfacción a cada uno de nuestros huéspedes.
                </p>
            </div>
        </div>
        <div class="row">

            <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center">                    
                        <i class="fa fa-broom"></i>
                    </div>
                    <h2 class="h5 mt-4 text-center">Servicio de Limpieza</h2>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fa fa-lock"></i></div>
                    <h2 class="h5 mt-4 text-center">Servicios de Seguridad</h2>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fa fa-calendar"></i></div>
                    <h2 class="h5 mt-4 text-center">Eventos y Ceremonias</h2>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fa fa-user"></i></div>
                    <h2 class="h5 mt-4 text-center">24 Hours Service</h2>
                </div>
            </div>
        </div>
    </section>
    <!-- End Section -->

    

VillaLuxeMvcNet/Views/Home/HomeVilla.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

VillaLuxeMvcNet/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@if (TempData["BienvenidaUsuario"] != null)
{
        <div class="alert alert-success">
        @TempData["BienvenidaUsuario"]
        </div>
}


    <!-- Start Banner Hero -->
    <div id="template-mo-zay-hero-carousel" class="carousel slide" data-bs-ride="carousel">
        <ol class="carousel-indicators">
            <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="0" class="active"></li>
            <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="1"></li>
            <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="container" id="container1">
                    <div class="row p-5">
                        <!-- <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                            <img class="img-fluid" src="../assets/img/banner_img_01.png" alt="">
                        </div> -->
                        @* <div class="col-lg-6"></div> *@
                        <div class="col-lg-6 mb-0 d-flex align-items-center">
                            <div class="text-align-left">
                                <h1 class="h1 text-white"><b>FANTÁSTICAS VILLAS EN LAS MEJORES UBICACIONES MÁS DESEADAS</b></h1>
                                <hr>
                                <!-- <p>
                                    Son una explosión de sabores auténticos y frescos, preparados con ingredientes de calidad para abrir tu apetito y emocionar tus papilas gustativas desde el primer bocado.
                                </p> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container" id="container2">
                    <div class="row p-5">
                        <!-- <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                            <img class="img-fluid" src="../assets/img/banner_img_02.png" alt="">
                        </div> -->
                        <div class="col-lg-6 mb-0 d-flex align-items-center">
                            <div class="text-align-left">
                                <h1 class="h1 text-white"><b>ESPACIOS CONFORTABLES Y COMODOS PARA LA MEJOR COMPAÑIA</b></h1>
                                <hr>
                                <!-- <p>
                                    Son una explosión de sabores auténticos y frescos, preparados con ingredientes de calidad para abrir tu apetito y emocionar tus papilas gustativas desde el primer bocado.
                                </p> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container" id="container3">
                    <div class="row p-5">
                        <!-- <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                            <img class="img-fluid" src="../assets/img/banner_img_03.png" alt="">
                        </div> -->
                        <!-- <div class="col-lg-6"></div> -->
                        <div class="col-lg-6 mb-0 d-flex align-items-center">
                            <div class="text-align-right">
                                <h1 class="h1 text-white"><b>VERDADEROS ATARDECERES QUE SIEMPRE HABÍAS SOÑADO</b></h1>
                                <hr>
                                <!-- <p>
                                    Son una tentación irresistiblemente dulce y exquisita, elaborados para deleitar tu paladar y culminar tu experiencia culinaria con un toque de felicidad.
                                </p> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev text-decoration-none w-auto ps-3" href="#template-mo-zay-hero-carousel" role="button" data-bs-slide="prev">
            <i class="fas fa-chevron-left" style="color: #a37d0b !important"></i>
        </a>
        <a class="carousel-control-next text-decoration-none w-auto pe-3" href="#template-mo-zay-hero-carousel" role="button" data-bs-slide="next">
            <i class="fas fa-chevron-right" style="color: #a37d0b !important"></i>
        </a>
    </div>
    <!-- End Banner Hero -->


    <!-- Start Categories of The Month -->
    <section class="container py-5">
        <div class="row text-center pt-2">
            <div class="col-lg-8 m-auto">
                <h1 class="h1"><b>NUESTRAS VILLAS ESTRELLA</b></h1>
                <p>
                    Estas exclusivas villas de lujo son estrellas por su ubicación privilegiada, vistas panorámicas impresionantes y diseño arquitectónico de vanguardia. Cada villa ofrece un oasis de privacidad y confort, equipada con servicios de primera clase y detalles personalizados para una experiencia única y memorable en cada estancia.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-4 p-6 mt-3">
                <a href="#"><img src="~/img/villa2_1.jpg" class=" img-fluid border"></a>
                <h5 class="text-center mt-3 mb-3">Villa Soulhouse</h5>
                <p class="text-center">
                    <a class="btn btn-danger" asp-controller="Villas" asp-action="DetallesVilla" asp-route-idvilla="2">
                        Detalles
                    </a>
                </p>
            </div>
            <div class="col-12 col-md-4 p-6 mt-3">
                <a href="#"><img src="~/img/villa6_1.jpg" class="img-fluid border"></a>
                <h2 class="h5 text-center mt-3 mb-3">Villa Sapphire</h2>
                <p class="text-center">
                    <a class="btn btn-danger" asp-controller="Villas" asp-action="DetallesVilla" asp-route-idvilla="6">
                        Detalles
                    </a>
                </p>
            </div>
            <div class="col-12 col-md-4 p-6 mt-3">
                <a href="#"><img src="~/img/villa4_1.jpg" class="img-fluid border"></a>
                <h2 class="h5 text-center mt-3 mb-3">Villa Binimi</h2>
                <p class="text-center">
                    <a class="btn btn-danger" asp-controller="Villas" asp-action="DetallesVilla" asp-route-idvilla="4">
                        Detalles
                    </a>
                </p>
            </div>
        </div>
    </section>