VillaLuxeMvcNet/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using VillaLuxeMvcNet.Models;
using VillaLuxeMvcNet.Services;
using VillaLuxeMvcNet.Repositories;
using Microsoft.AspNetCore.Identity;

namespace VillaLuxeMvcNet.Controllers
{
    public class ManagedController : Controller
    {
        private IRepositoryVillas service;
        public ManagedController(IRepositoryVillas service)
        {
            this.service = service;      
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(Usuario usu, string password)
        {
            RegisterModel register = new RegisterModel();
            register.Usuario = usu;
            register.Password = password;
            await this.service.RegisterUser(register);                                  
            TempData["RegistroExitoso"] = "Usuario registrado";
            return RedirectToAction("Login");
        }

        public IActionResult Login()
        {
            ViewData["MENSAJE"] = TempData["RegistroExitoso"]; // Pasar el mensaje de TempData a ViewData
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Login
     (string email, string password)
        {
            Usuario user = await
                this.service.FindUsuarioEmailPassword(email, password);
            string token = await this.service
                .GetTokenAsync(email, password);
            if (user != null)
            {
                //SEGURIDAD
                ClaimsIdentity identity =
                    new ClaimsIdentity(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        ClaimTypes.Name, ClaimTypes.Role);
                Claim claimName =
                    new Claim(ClaimTypes.Name, user.Nombre);
                Claim claimRole = new Claim(ClaimTypes.Role, user.IdRol.ToString());
                Claim claimIdUsuario = new Claim("IDUSUARIO", user.IdUsuario.ToString());
                Claim claimToken = new Claim("TOKEN", token);
                identity.AddClaim(claimRole);
                identity.AddClaim(claimName);
                identity.AddClaim(claimIdUsuario);
                identity.AddClaim(claimToken);
                ClaimsPrincipal userPrincipal =
                    new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    userPrincipal);
                TempData["BIENVENIDA"] = "Bienvenido " + user.Nombre;
                return RedirectToAction("Index", "Villas");
            }
            else
            {
                TempData["MENSAJE"] = "Credenciales incorrectas";
                return View();
            }
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync
                (CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Villas");
        }

    }
}

VillaLuxeMvcNet/Views/Managed/Login.cshtml
@model Usuario

@if (TempData["RegistroExitoso"] != null)
{
    <div class="alert alert-success">
        @TempData["RegistroExitoso"]
    </div>
}

@if (TempData["MENSAJE"] != null)
{
    <div class="alert alert-danger">
        @TempData["MENSAJE"]
    </div>
}

<div style="display: flex; justify-content: center; padding-top: 100px; padding-bottom: 100px;">
    <form class="form" method="post">
        <p class="title">Inicia sesión </p>
        <label>
            <input required="" placeholder="" type="text" class="input" name="email">
            <span>Email</span>
        </label>

        <label>
            <input required="" placeholder="" type="password" class="input" name="password">
            <span>Contraseña</span>
        </label>

        <button class="submit">Conéctate</button>
        <p class="signin">
            ¿No tienes cuenta todavía?
            <a asp-area="" asp-controller="Managed" asp-action="Register">Registrarse</a>
        </p>
    </form>
</div>

VillaLuxeMvcNet/Views/Managed/Register.cshtml
<div style="display: flex; justify-content: center; padding-top: 50px; padding-bottom: 50px;">
    <form class="form" method="post">
        <p class="title">Registro </p>
        <p class="message">Registrate ahora para poder reservar siempre que quieras</p>
        <div class="flex">
            <label>
                <input required="" placeholder="" type="text" class="input" name="nombre">
                <span>Nombre</span>
            </label>

            <label>
                <input required="" placeholder="" type="text" class="input" name="telefono">
                <span>Telefono</span>
            </label>
        </div>

        <label>
            <input required="" placeholder="" type="email" class="input" name="email">
            <span>Email</span>
        </label>

        <label>
            <input required="" placeholder="" type="password" class="input" name="password">
            <span>Contraseña</span>
        </label>
        <label>
            <input required="" placeholder="" type="password" class="input">
            <span>Confirm password</span>
        </label>
        <button class="submit">Submit</button>
        <p class="signin">
            ¿Ya tienes una cuenta?
            <a asp-area="" asp-controller="Managed" asp-action="Login">Inicia sesión</a>
        </p>
    </form>
</div>